### ISSUE TITLE
change patch numbering order

### ISSUE THREAD

**Issue by konus1** [grantemsley/dokuwiki-plugin-patchpanel#5]
There are some switches on the market with a different numbering schema.
Instead of 
01,02,03,04,05,06,07,08,09,10,11,12
13,14,15,16,17,18,19,20,21,22,23,24

they have
01,03,05,07,09,11,13,15,17,19,21,23
02,04,06,08,10,12,14,16,18,20,22,24
(i.e. HP, Netgear, TP-Link, DLink, Nortel, Force10))

it would be nice, if the plugin could used for them too.

Note: I also found on the net the follwoing numbering schema, but don't know, how common they are:
13,14,15,16,17,18,19,20,21,22,23,24
01,02,03,04,05,06,07,08,09,10,11,12
and 
02,04,06,08,10,12,14,16,18,20,22,24
01,03,05,07,09,11,13,15,17,19,21,23
(LevelOne, ZyXEL))

**Comment by fiveninezero** [comment]
Well, i don't really care for beer. So ... please donate :)

**Comment by konus1** [comment]
OK, I have donated it do dokuwiki. Thank you for your help!
